### ISSUE TITLE
Snowflake test database

### ISSUE THREAD

**Issue by ablack3** [OHDSI/OpenSourceCommunity#1]
OHDSI developers need to be able to test code on all supported database platforms. Snowflake is now a supported platform but there is not yet a test environment for it. 

The requirements for the environment are:
- cdm schema with a synpuf 5.3 cdm
- cdm schema with a synpuf 5.4 cdm
- scratch schema where developers can test creation of persistent tables (This should be cleaned up automatically on a daily or weekly basis)

@konstjar, @leeevans - Are you setting this up? Any timeline on when it will be ready?

**Comment by ablack3** [comment]
It would be nice if the CDM data that was used in each test environment was the same and each database had a "scratch" schema where we could test creation of permanent tables.

**Comment by konstjar** [comment]
Hey @ablack3 As you know we are still working on long term solution. But right now there is a temporary one.
It's possible to request a trial 120-days account in AWS: https://signup.snowflake.com/?trial=student
Please use east-1 region and we will be able to share SynPUF dataset with your account.

**Comment by ablack3** [comment]
Thanks @konstjar.

**Comment by konstjar** [comment]
We can close it as there is test instance that could be used by community.
