### ISSUE TITLE
visit_detail table missing on SQL Server 5.3 test database

### ISSUE THREAD

**Issue by ablack3** [OHDSI/OpenSourceCommunity#2]
The visit_detail table is not required so maybe this ok. The visit_detail table is missing in the v5.3 CDM test database on SQL Server. (schema cdmv5.dbo)

**Comment by ablack3** [comment]
![image](https://user-images.githubusercontent.com/10227522/211587324-9b74232f-b71b-4690-92f9-2a9f7364ae62.png)


@leeevans, my understanding is that visit_detail is not required to be populated but is required to exist with the correct column names and types.

**Comment by leeevans** [comment]
created
