### ISSUE TITLE
SQL server CDM 5.3 test database person table missing person_birthdatetime.

### ISSUE THREAD

**Issue by ablack3** [OHDSI/OpenSourceCommunity#3]
The [CDM 5.3 spec](https://ohdsi.github.io/CommonDataModel/cdm53.html#PERSON) has a birth_datetime column in the person table. 

The SQL server 5.3 test database has a "time_of_birth" column (not in the spec) and does not have birth_datetime.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/10227522/203169253-38e5a252-2bfa-4ad9-8bc8-51b826d8777c.png">

Tagging @leeevans

**Comment by ablack3** [comment]
@leeevans is it possible to fix this?

**Comment by leeevans** [comment]
completed
