### ISSUE TITLE
Increase number of allowed temp tables on Oracle test database

### ISSUE THREAD

**Issue by ablack3** [OHDSI/OpenSourceCommunity#5]
Oracle v18, initially released in 2018, added support for [private temporary tables](https://oracle-base.com/articles/18c/private-temporary-tables-18c). However by default there is a limit of 16 tables. @leeevans Would it be possible to increase the number of allowed private temporary tables on the Oracle test database by running the following SQL command on the OHDSI Oracle test database?
`ALTER SYSTEM SET "_ptt_max_num"=64 SCOPE = BOTH;`

Admin permissions are required to change this setting.

**Comment by leeevans** [comment]
@ablack3 It's an AWS RDS database which means there are some limits on what the master user can do:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.MasterAccounts.html

When I run the command as the master user I get this error message:

```
Error starting at line : 1 in command -
ALTER SYSTEM SET "_ptt_max_num"=64 SCOPE = BOTH
Error report -
SQL Error: ORA-01031: insufficient privileges
01031. 00000 -  "insufficient privileges"
*Cause:    An attempt was made to change the current username or password
           without the appropriate privilege. This error also occurs if
           attempting to install a database without the necessary operating
           system privileges.
           When Trusted Oracle is configure in DBMS MAC, this error may occur
           if the user was granted the necessary privilege at a higher label
           than the current login.
*Action:   Ask the database administrator to perform the operation or grant
           the required privileges.
           For Trusted Oracle users getting this error although granted the
           the appropriate privilege at a higher label, ask the database
           administrator to regrant the privilege at the appropriate label.
```

I don't see any admin utility stored proc function (rdsadmin.rdsadmin_util) from the AWS RDS service to set that parameter:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.Oracle.CommonDBATasks.html
