### ISSUE TITLE
Oracle 5.3 test cdm has person.time_of_birth but is missing person.birth_datetime

### ISSUE THREAD

**Issue by ablack3** [OHDSI/OpenSourceCommunity#6]
Oracle 5.3 test cdm has person.time_of_birth but is missing person.birth_datetime

<img width="907" alt="image" src="https://user-images.githubusercontent.com/10227522/223228718-69999890-086e-4069-98e3-8c8fecfd1189.png">

**Comment by leeevans** [comment]
completed
